import { db } from "@workspace/db";
import { movesTable, pokemonSpeciesTable, regionsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

const NEW_MOVES = [
  // Fire/Water (Volcanion style)
  { name: "Steam Eruption", type: "Water", power: 110, accuracy: 95, pp: 5, category: "special", description: "The user immerses the target in superheated steam. This may also leave the target with a burn." },
  { name: "Flare Blitz", type: "Fire", power: 120, accuracy: 100, pp: 15, category: "physical", description: "The user cloaks itself in fire and charges the target. This also damages the user quite a lot." },
  // Ground/Flying
  { name: "Scary Face", type: "Normal", power: 0, accuracy: 100, pp: 10, category: "special", description: "The user frightens the target with a scary face to harshly lower its Speed stat." },
  { name: "Sky Attack", type: "Flying", power: 140, accuracy: 90, pp: 5, category: "physical", description: "A second-turn attack move where critical hits land more easily. This may also make the target flinch." },
  // Ghost/Electric
  { name: "Discharge", type: "Electric", power: 80, accuracy: 100, pp: 15, category: "special", description: "The user strikes everything around it by letting loose a flare of electricity. This may also cause paralysis." },
  { name: "Hex", type: "Ghost", power: 65, accuracy: 100, pp: 10, category: "special", description: "This relentless attack does massive damage to a target affected by status conditions." },
  // Ice/Grass
  { name: "Frost Breath", type: "Ice", power: 60, accuracy: 90, pp: 10, category: "special", description: "The user blows its cold breath on the target. This attack always results in a critical hit." },
  { name: "Petal Dance", type: "Grass", power: 120, accuracy: 100, pp: 10, category: "special", description: "The user attacks by scattering petals for two to three turns. The user then becomes confused." },
  // Dragon/Fire
  { name: "Dragon Pulse", type: "Dragon", power: 85, accuracy: 100, pp: 10, category: "special", description: "The target is attacked with a shock wave generated by the user's gaping mouth." },
  { name: "Blue Flare", type: "Fire", power: 130, accuracy: 85, pp: 5, category: "special", description: "The user engulfs the target in an intense, yet beautiful, blue flame. This may also leave the target with a burn." },
  // Psychic/Ground
  { name: "Earth Power", type: "Ground", power: 90, accuracy: 100, pp: 10, category: "special", description: "The user makes the ground under the target erupt with power. This may also lower the target's Sp. Def stat." },
  { name: "Psyshock", type: "Psychic", power: 80, accuracy: 100, pp: 10, category: "special", description: "The user materializes an odd psychic wave to attack the target. This attack deals physical damage." },
  // Water/Electric
  { name: "Volt Switch", type: "Electric", power: 70, accuracy: 100, pp: 20, category: "special", description: "After making its attack, the user rushes back to switch places with a party Pokemon in waiting." },
  { name: "Liquidation", type: "Water", power: 85, accuracy: 100, pp: 10, category: "physical", description: "The user slams into the target using a full-force blast of water. This may also lower the target's Defense stat." },
  // Flying/Ghost
  { name: "Air Cutter", type: "Flying", power: 60, accuracy: 95, pp: 25, category: "special", description: "The user launches razor-like wind to slash opposing Pokemon. Critical hits land more easily." },
  { name: "Shadow Sneak", type: "Ghost", power: 40, accuracy: 100, pp: 30, category: "physical", description: "The user extends its shadow and attacks the target from behind. This move always goes first." },
  // Grass/Fire
  { name: "Magical Leaf", type: "Grass", power: 60, accuracy: 110, pp: 20, category: "special", description: "The user scatters curious leaves that chase the target. This attack never misses." },
  { name: "Leaf Storm", type: "Grass", power: 130, accuracy: 90, pp: 5, category: "special", description: "The user whips up a storm of leaves around the target. The attack's recoil harshly lowers the user's Sp. Atk stat." },
  // Ice/Dragon
  { name: "Freeze-Dry", type: "Ice", power: 70, accuracy: 100, pp: 20, category: "special", description: "The user rapidly cools the target. This move is super effective on Water types." },
  { name: "Glaive Rush", type: "Dragon", power: 120, accuracy: 100, pp: 5, category: "physical", description: "The user throws itself at the target to inflict damage. On the next turn, attacks will always hit the user." },
  // Ground/Ghost
  { name: "Phantom Force", type: "Ghost", power: 90, accuracy: 100, pp: 10, category: "physical", description: "The user vanishes, then strikes the target on the next turn. This move hits even if the target used Protect." },
  { name: "High Horsepower", type: "Ground", power: 95, accuracy: 95, pp: 10, category: "physical", description: "The user fiercely slams into the target with its entire body." },
  // Electric/Psychic
  { name: "Psychic Fangs", type: "Psychic", power: 85, accuracy: 100, pp: 10, category: "physical", description: "The user bites the target with its psychic capabilities. This move destroys Reflect and Light Screen." },
  { name: "Wild Charge", type: "Electric", power: 90, accuracy: 100, pp: 15, category: "physical", description: "The user shrouds itself in electricity and smashes into its target. This also damages the user a little." },
  // Flying/Ice
  { name: "Acrobatics", type: "Flying", power: 55, accuracy: 100, pp: 15, category: "physical", description: "The user nimbly strikes the target. If the user is not holding an item, this attack inflicts massive damage." },
  { name: "Icicle Crash", type: "Ice", power: 85, accuracy: 90, pp: 10, category: "physical", description: "The user attacks by crashing large icicles onto the target. This may also make the target flinch." },
  // Water/Grass
  { name: "Giga Drain", type: "Grass", power: 75, accuracy: 100, pp: 10, category: "special", description: "A nutrient-draining attack. The user's HP is restored by half the damage taken by the target." },
  { name: "Scald", type: "Water", power: 80, accuracy: 100, pp: 15, category: "special", description: "The user shoots boiling hot water at its target. This may also leave the target with a burn." },
  // Fire/Psychic
  { name: "Mystical Fire", type: "Fire", power: 75, accuracy: 100, pp: 10, category: "special", description: "The user attacks by breathing a special, hot fire. This also lowers the target's Sp. Atk stat." },
  { name: "Psyshock", type: "Psychic", power: 80, accuracy: 100, pp: 10, category: "special", description: "The user materializes an odd psychic wave to attack the target. This attack deals physical damage." },
];

const NEW_SPECIES = [
  {
    name: "Growlithe",
    description: "It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.",
    type1: "Fire", type2: null,
    baseHp: 55, baseAttack: 70, baseDefense: 45, baseSpeed: 60, baseSpecialAttack: 70, baseSpecialDefense: 50,
    evolutionLevel: 25, catchRate: 190, rarity: "common",
    spriteUrl: "/api/sprites/growlithe", backSpriteUrl: "/api/sprites/growlithe-back",
    moveNames: ["Ember", "Flamethrower", "Fire Punch"],
  },
  {
    name: "Arcanine",
    description: "The sight of it running over 6,200 miles in a single day and night has captivated many people.",
    type1: "Fire", type2: null,
    baseHp: 90, baseAttack: 110, baseDefense: 80, baseSpeed: 95, baseSpecialAttack: 100, baseSpecialDefense: 80,
    evolutionLevel: null, catchRate: 75, rarity: "rare",
    spriteUrl: "/api/sprites/arcanine", backSpriteUrl: "/api/sprites/arcanine-back",
    moveNames: ["Flare Blitz", "Flamethrower", "Fire Blast", "Ember"],
  },
  {
    name: "Gligar",
    description: "It flies straight at its target's face, then clamps down on the startled victim to inject poison.",
    type1: "Ground", type2: "Flying",
    baseHp: 65, baseAttack: 75, baseDefense: 105, baseSpeed: 85, baseSpecialAttack: 35, baseSpecialDefense: 65,
    evolutionLevel: 30, catchRate: 60, rarity: "common",
    spriteUrl: "/api/sprites/gligar", backSpriteUrl: "/api/sprites/gligar-back",
    moveNames: ["Sky Attack", "Earthquake", "Gust"],
  },
  {
    name: "Gliscor",
    description: "It hangs upside down from branches. When it spots prey, it swoops down and strikes with its tail.",
    type1: "Ground", type2: "Flying",
    baseHp: 75, baseAttack: 95, baseDefense: 125, baseSpeed: 95, baseSpecialAttack: 45, baseSpecialDefense: 75,
    evolutionLevel: null, catchRate: 30, rarity: "rare",
    spriteUrl: "/api/sprites/gliscor", backSpriteUrl: "/api/sprites/gliscor-back",
    moveNames: ["Earthquake", "Sky Attack", "Air Slash", "Sand Tomb"],
  },
  {
    name: "Rotom",
    description: "Its body is composed of plasma. It is known to infiltrate electronic devices and wreak havoc.",
    type1: "Electric", type2: "Ghost",
    baseHp: 50, baseAttack: 50, baseDefense: 77, baseSpeed: 91, baseSpecialAttack: 95, baseSpecialDefense: 77,
    evolutionLevel: null, catchRate: 45, rarity: "uncommon",
    spriteUrl: "/api/sprites/rotom", backSpriteUrl: "/api/sprites/rotom-back",
    moveNames: ["Discharge", "Shadow Ball", "Thunderbolt"],
  },
  {
    name: "Luxio",
    description: "Strong electricity kurses through the tips of its sharp claws. A light scratch can cause fainting.",
    type1: "Electric", type2: null,
    baseHp: 60, baseAttack: 85, baseDefense: 49, baseSpeed: 60, baseSpecialAttack: 60, baseSpecialDefense: 49,
    evolutionLevel: 30, catchRate: 120, rarity: "uncommon",
    spriteUrl: "/api/sprites/luxio", backSpriteUrl: "/api/sprites/luxio-back",
    moveNames: ["Spark", "Thunderbolt", "Bite"],
  },
  {
    name: "Luxray",
    description: "When its eyes gleam gold, it can spot hiding prey—even those taking shelter behind a thick wall.",
    type1: "Electric", type2: null,
    baseHp: 80, baseAttack: 120, baseDefense: 79, baseSpeed: 70, baseSpecialAttack: 95, baseSpecialDefense: 79,
    evolutionLevel: null, catchRate: 45, rarity: "rare",
    spriteUrl: "/api/sprites/luxray", backSpriteUrl: "/api/sprites/luxray-back",
    moveNames: ["Wild Charge", "Thunderbolt", "Spark", "Crunch"],
  },
  {
    name: "Absol",
    description: "It has the ability to foretell natural disasters. It lives in mountain ranges where few people venture.",
    type1: "Dark", type2: null,
    baseHp: 65, baseAttack: 130, baseDefense: 60, baseSpeed: 75, baseSpecialAttack: 75, baseSpecialDefense: 60,
    evolutionLevel: null, catchRate: 30, rarity: "rare",
    spriteUrl: "/api/sprites/absol", backSpriteUrl: "/api/sprites/absol-back",
    moveNames: ["Dark Pulse", "Crunch", "Bite", "Psychic Fangs"],
  },
  {
    name: "Snover",
    description: "In the spring, it grows berries with the texture of frozen treats around its belly.",
    type1: "Grass", type2: "Ice",
    baseHp: 60, baseAttack: 62, baseDefense: 50, baseSpeed: 40, baseSpecialAttack: 62, baseSpecialDefense: 60,
    evolutionLevel: 40, catchRate: 120, rarity: "common",
    spriteUrl: "/api/sprites/snover", backSpriteUrl: "/api/sprites/snover-back",
    moveNames: ["Ice Shard", "Razor Leaf", "Frost Breath"],
  },
  {
    name: "Abomasnow",
    description: "It blankets wide areas in snow by whipping up blizzards. It is also known as the Ice Monster.",
    type1: "Grass", type2: "Ice",
    baseHp: 90, baseAttack: 92, baseDefense: 75, baseSpeed: 60, baseSpecialAttack: 92, baseSpecialDefense: 85,
    evolutionLevel: null, catchRate: 60, rarity: "rare",
    spriteUrl: "/api/sprites/abomasnow", backSpriteUrl: "/api/sprites/abomasnow-back",
    moveNames: ["Blizzard", "Petal Dance", "Ice Beam", "Energy Ball"],
  },
  {
    name: "Turtonator",
    description: "The shell on its back is chemically unstable and explodes if struck. The hole in its stomach is its weak point.",
    type1: "Fire", type2: "Dragon",
    baseHp: 60, baseAttack: 78, baseDefense: 135, baseSpeed: 36, baseSpecialAttack: 91, baseSpecialDefense: 85,
    evolutionLevel: null, catchRate: 70, rarity: "uncommon",
    spriteUrl: "/api/sprites/turtonator", backSpriteUrl: "/api/sprites/turtonator-back",
    moveNames: ["Dragon Pulse", "Flamethrower", "Fire Blast"],
  },
  {
    name: "Reshiram",
    description: "This Pokemon appears in legends. It sends flames into the air from its tail, burning up everything around it.",
    type1: "Dragon", type2: "Fire",
    baseHp: 100, baseAttack: 120, baseDefense: 100, baseSpeed: 90, baseSpecialAttack: 150, baseSpecialDefense: 120,
    evolutionLevel: null, catchRate: 3, rarity: "legendary",
    spriteUrl: "/api/sprites/reshiram", backSpriteUrl: "/api/sprites/reshiram-back",
    moveNames: ["Blue Flare", "Dragon Pulse", "Fire Blast", "Psychic"],
  },
  {
    name: "Baltoy",
    description: "It moves by spinning on its foot. It is often found in prehistoric ruins.",
    type1: "Ground", type2: "Psychic",
    baseHp: 40, baseAttack: 40, baseDefense: 55, baseSpeed: 55, baseSpecialAttack: 40, baseSpecialDefense: 70,
    evolutionLevel: 36, catchRate: 190, rarity: "uncommon",
    spriteUrl: "/api/sprites/baltoy", backSpriteUrl: "/api/sprites/baltoy-back",
    moveNames: ["Confusion", "Mud-Slap", "Earth Power"],
  },
  {
    name: "Claydol",
    description: "It is said to have originated from a clay doll made by ancient people over 20,000 years ago.",
    type1: "Ground", type2: "Psychic",
    baseHp: 60, baseAttack: 70, baseDefense: 105, baseSpeed: 75, baseSpecialAttack: 70, baseSpecialDefense: 120,
    evolutionLevel: null, catchRate: 90, rarity: "rare",
    spriteUrl: "/api/sprites/claydol", backSpriteUrl: "/api/sprites/claydol-back",
    moveNames: ["Earth Power", "Psychic", "Psyshock", "Earthquake"],
  },
  {
    name: "Chinchou",
    description: "It discharges positive and negative electricity from its two antennae to stun its prey.",
    type1: "Water", type2: "Electric",
    baseHp: 75, baseAttack: 38, baseDefense: 38, baseSpeed: 67, baseSpecialAttack: 56, baseSpecialDefense: 56,
    evolutionLevel: 26, catchRate: 190, rarity: "common",
    spriteUrl: "/api/sprites/chinchou", backSpriteUrl: "/api/sprites/chinchou-back",
    moveNames: ["Water Gun", "Thunder Shock", "Volt Switch"],
  },
  {
    name: "Lanturn",
    description: "It blinds prey with an intense burst of light, then swallows them whole while they're dazed.",
    type1: "Water", type2: "Electric",
    baseHp: 125, baseAttack: 58, baseDefense: 58, baseSpeed: 67, baseSpecialAttack: 76, baseSpecialDefense: 76,
    evolutionLevel: null, catchRate: 75, rarity: "rare",
    spriteUrl: "/api/sprites/lanturn", backSpriteUrl: "/api/sprites/lanturn-back",
    moveNames: ["Hydro Pump", "Thunderbolt", "Volt Switch", "Surf"],
  },
  {
    name: "Drifloon",
    description: "It is said that any child who mistakes it for a balloon and holds on to it could wind up missing.",
    type1: "Ghost", type2: "Flying",
    baseHp: 90, baseAttack: 50, baseDefense: 34, baseSpeed: 70, baseSpecialAttack: 60, baseSpecialDefense: 44,
    evolutionLevel: 28, catchRate: 125, rarity: "uncommon",
    spriteUrl: "/api/sprites/drifloon", backSpriteUrl: "/api/sprites/drifloon-back",
    moveNames: ["Gust", "Lick", "Shadow Ball"],
  },
  {
    name: "Drifblim",
    description: "It can carry people and Pokemon, but it cannot control its flight at all. It just drifts with the wind.",
    type1: "Ghost", type2: "Flying",
    baseHp: 150, baseAttack: 80, baseDefense: 44, baseSpeed: 80, baseSpecialAttack: 90, baseSpecialDefense: 54,
    evolutionLevel: null, catchRate: 60, rarity: "rare",
    spriteUrl: "/api/sprites/drifblim", backSpriteUrl: "/api/sprites/drifblim-back",
    moveNames: ["Shadow Ball", "Hurricane", "Phantom Force", "Air Cutter"],
  },
  {
    name: "Capsakid",
    description: "Traditional Paldean cuisine uses the shed teeth of Capsakid to add a spicy kick to dishes.",
    type1: "Grass", type2: null,
    baseHp: 50, baseAttack: 62, baseDefense: 40, baseSpeed: 50, baseSpecialAttack: 62, baseSpecialDefense: 40,
    evolutionLevel: 30, catchRate: 190, rarity: "common",
    spriteUrl: "/api/sprites/capsakid", backSpriteUrl: "/api/sprites/capsakid-back",
    moveNames: ["Vine Whip", "Ember", "Leaf Storm"],
  },
  {
    name: "Scovillain",
    description: "Its red head converts spicy chemicals into fiery energy, while its green head takes control of that energy.",
    type1: "Grass", type2: "Fire",
    baseHp: 65, baseAttack: 108, baseDefense: 65, baseSpeed: 75, baseSpecialAttack: 108, baseSpecialDefense: 65,
    evolutionLevel: null, catchRate: 75, rarity: "rare",
    spriteUrl: "/api/sprites/scovillain", backSpriteUrl: "/api/sprites/scovillain-back",
    moveNames: ["Leaf Storm", "Flamethrower", "Solar Beam", "Fire Blast"],
  },
  {
    name: "Frigibax",
    description: "It absorbs heat through the dorsal fin on its back and converts the heat into ice energy.",
    type1: "Dragon", type2: "Ice",
    baseHp: 54, baseAttack: 75, baseDefense: 45, baseSpeed: 50, baseSpecialAttack: 35, baseSpecialDefense: 45,
    evolutionLevel: 35, catchRate: 45, rarity: "uncommon",
    spriteUrl: "/api/sprites/frigibax", backSpriteUrl: "/api/sprites/frigibax-back",
    moveNames: ["Dragon Breath", "Ice Shard", "Dragon Claw"],
  },
  {
    name: "Baxcalibur",
    description: "It finishes off its foes with a single blow from its ice-covered dorsal fin, which is as sharp as a sword.",
    type1: "Dragon", type2: "Ice",
    baseHp: 115, baseAttack: 145, baseDefense: 92, baseSpeed: 87, baseSpecialAttack: 75, baseSpecialDefense: 86,
    evolutionLevel: null, catchRate: 10, rarity: "rare",
    spriteUrl: "/api/sprites/baxcalibur", backSpriteUrl: "/api/sprites/baxcalibur-back",
    moveNames: ["Glaive Rush", "Icicle Crash", "Dragon Claw", "Blizzard"],
  },
  {
    name: "Golett",
    description: "It was created from clay by people of long ago. It is perpetually powered by an unknown energy source.",
    type1: "Ground", type2: "Ghost",
    baseHp: 59, baseAttack: 74, baseDefense: 50, baseSpeed: 35, baseSpecialAttack: 35, baseSpecialDefense: 50,
    evolutionLevel: 43, catchRate: 190, rarity: "common",
    spriteUrl: "/api/sprites/golett", backSpriteUrl: "/api/sprites/golett-back",
    moveNames: ["Mud-Slap", "Shadow Claw", "High Horsepower"],
  },
  {
    name: "Golurk",
    description: "It flies across the sky at Mach speeds. Removing the seal on its chest makes its internal energy go out of control.",
    type1: "Ground", type2: "Ghost",
    baseHp: 89, baseAttack: 124, baseDefense: 80, baseSpeed: 55, baseSpecialAttack: 55, baseSpecialDefense: 80,
    evolutionLevel: null, catchRate: 90, rarity: "rare",
    spriteUrl: "/api/sprites/golurk", backSpriteUrl: "/api/sprites/golurk-back",
    moveNames: ["High Horsepower", "Phantom Force", "Earthquake", "Shadow Ball"],
  },
  {
    name: "Magnemite",
    description: "It floats in the air by emitting electromagnetic waves. It can cause power outages if many of them gather.",
    type1: "Electric", type2: "Steel",
    baseHp: 25, baseAttack: 35, baseDefense: 70, baseSpeed: 45, baseSpecialAttack: 95, baseSpecialDefense: 55,
    evolutionLevel: 30, catchRate: 190, rarity: "uncommon",
    spriteUrl: "/api/sprites/magnemite", backSpriteUrl: "/api/sprites/magnemite-back",
    moveNames: ["Thunder Shock", "Spark", "Thunderbolt"],
  },
  {
    name: "Magnezone",
    description: "It evolved due to a special magnetic field. Three units bond together to form this Pokemon.",
    type1: "Electric", type2: "Steel",
    baseHp: 70, baseAttack: 70, baseDefense: 115, baseSpeed: 60, baseSpecialAttack: 130, baseSpecialDefense: 90,
    evolutionLevel: null, catchRate: 30, rarity: "rare",
    spriteUrl: "/api/sprites/magnezone", backSpriteUrl: "/api/sprites/magnezone-back",
    moveNames: ["Discharge", "Flash Cannon", "Thunderbolt", "Wild Charge"],
  },
  {
    name: "Delibird",
    description: "It carries food all day long. There are tales about lost people being saved by the food it had.",
    type1: "Ice", type2: "Flying",
    baseHp: 45, baseAttack: 55, baseDefense: 45, baseSpeed: 75, baseSpecialAttack: 65, baseSpecialDefense: 45,
    evolutionLevel: null, catchRate: 45, rarity: "common",
    spriteUrl: "/api/sprites/delibird", backSpriteUrl: "/api/sprites/delibird-back",
    moveNames: ["Ice Shard", "Present", "Acrobatics"],
  },
  {
    name: "Articuno",
    description: "A legendary bird Pokemon. It can create blizzards by freezing moisture in the air.",
    type1: "Ice", type2: "Flying",
    baseHp: 90, baseAttack: 85, baseDefense: 100, baseSpeed: 85, baseSpecialAttack: 95, baseSpecialDefense: 125,
    evolutionLevel: null, catchRate: 3, rarity: "legendary",
    spriteUrl: "/api/sprites/articuno", backSpriteUrl: "/api/sprites/articuno-back",
    moveNames: ["Blizzard", "Hurricane", "Ice Beam", "Air Slash"],
  },
  {
    name: "Lotad",
    description: "It lives in clean-water ponds and lakes. It is sometimes mistaken for a water lily.",
    type1: "Water", type2: "Grass",
    baseHp: 40, baseAttack: 30, baseDefense: 30, baseSpeed: 30, baseSpecialAttack: 40, baseSpecialDefense: 50,
    evolutionLevel: 14, catchRate: 255, rarity: "common",
    spriteUrl: "/api/sprites/lotad", backSpriteUrl: "/api/sprites/lotad-back",
    moveNames: ["Water Gun", "Vine Whip", "Giga Drain"],
  },
  {
    name: "Ludicolo",
    description: "If it hears festive music, it begins moving in rhythm in order to amplify its power.",
    type1: "Water", type2: "Grass",
    baseHp: 80, baseAttack: 70, baseDefense: 70, baseSpeed: 70, baseSpecialAttack: 90, baseSpecialDefense: 100,
    evolutionLevel: null, catchRate: 45, rarity: "rare",
    spriteUrl: "/api/sprites/ludicolo", backSpriteUrl: "/api/sprites/ludicolo-back",
    moveNames: ["Hydro Pump", "Giga Drain", "Scald", "Petal Dance"],
  },
  {
    name: "Braixen",
    description: "It has a twig stuck in its tail. By friction, it sets the twig on fire and uses it like a magic wand.",
    type1: "Fire", type2: null,
    baseHp: 59, baseAttack: 59, baseDefense: 58, baseSpeed: 73, baseSpecialAttack: 90, baseSpecialDefense: 70,
    evolutionLevel: 36, catchRate: 45, rarity: "uncommon",
    spriteUrl: "/api/sprites/braixen", backSpriteUrl: "/api/sprites/braixen-back",
    moveNames: ["Flamethrower", "Psychic", "Mystical Fire"],
  },
  {
    name: "Delphox",
    description: "It gazes into the flame at the tip of its branch to achieve a focused state, which allows it to see into the future.",
    type1: "Fire", type2: "Psychic",
    baseHp: 75, baseAttack: 69, baseDefense: 72, baseSpeed: 104, baseSpecialAttack: 114, baseSpecialDefense: 100,
    evolutionLevel: null, catchRate: 45, rarity: "rare",
    spriteUrl: "/api/sprites/delphox", backSpriteUrl: "/api/sprites/delphox-back",
    moveNames: ["Mystical Fire", "Psychic", "Fire Blast", "Psyshock"],
  },
];

export async function expand() {
  console.log("Starting Pokemon expansion...");

  // Insert any currently missing moves
  const existingMoves = await db.select().from(movesTable);
  const existingMoveNames = new Set(existingMoves.map((m: any) => m.name));
  
  const movesToInsert = NEW_MOVES.filter((m) => !existingMoveNames.has(m.name));
  if (movesToInsert.length > 0) {
    console.log(`Inserting ${movesToInsert.length} new unique moves...`);
    await db.insert(movesTable).values(movesToInsert);
  } else {
    console.log("New moves already exist.");
  }

  // Refetch all moves to get maps
  const allMoves = await db.select().from(movesTable);
  const moveMap = new Map(allMoves.map((m: any) => [m.name, m.id]));

  // Insert any currently missing species
  const existingSpecies = await db.select().from(pokemonSpeciesTable);
  const existingSpeciesNames = new Set(existingSpecies.map((s: any) => s.name));

  const evolutionLinks: Array<{ name: string; evolvesFrom: string }> = [
    { name: "Arcanine", evolvesFrom: "Growlithe" },
    { name: "Gliscor", evolvesFrom: "Gligar" },
    { name: "Luxio", evolvesFrom: "Shinx" },
    { name: "Luxray", evolvesFrom: "Luxio" },
    
    { name: "Reshiram", evolvesFrom: "Turtonator" },
    { name: "Claydol", evolvesFrom: "Baltoy" },
    { name: "Lanturn", evolvesFrom: "Chinchou" },
    { name: "Drifblim", evolvesFrom: "Drifloon" },
    { name: "Scovillain", evolvesFrom: "Capsakid" },
    { name: "Baxcalibur", evolvesFrom: "Frigibax" },
    { name: "Golurk", evolvesFrom: "Golett" },
    { name: "Magnezone", evolvesFrom: "Magnemite" },
    { name: "Ludicolo", evolvesFrom: "Lotad" },
    { name: "Delphox", evolvesFrom: "Braixen" },
  ];

  const speciesToInsert = NEW_SPECIES.filter((s) => !existingSpeciesNames.has(s.name));
  if (speciesToInsert.length > 0) {
    console.log(`Inserting ${speciesToInsert.length} new species...`);
    const speciesInserts = speciesToInsert.map((s) => ({
      name: s.name,
      description: s.description,
      type1: s.type1,
      type2: s.type2 ?? null,
      baseHp: s.baseHp,
      baseAttack: s.baseAttack,
      baseDefense: s.baseDefense,
      baseSpeed: s.baseSpeed,
      baseSpecialAttack: s.baseSpecialAttack,
      baseSpecialDefense: s.baseSpecialDefense,
      evolutionLevel: s.evolutionLevel ?? null,
      evolvesIntoId: null as number | null,
      catchRate: s.catchRate,
      spriteUrl: s.spriteUrl,
      backSpriteUrl: s.backSpriteUrl,
      moveIds: (s.moveNames ?? []).map((mn) => moveMap.get(mn) ?? 1),
      rarity: s.rarity,
    }));

    await db.insert(pokemonSpeciesTable).values(speciesInserts);
  } else {
    console.log("New species already exist.");
  }

  // Refetch all species for evolution links and region spawns
  const allSpecies = await db.select().from(pokemonSpeciesTable);
  const speciesMap = new Map(allSpecies.map((s: any) => [s.name, s.id]));

  console.log("Updating evolution links...");
  for (const link of evolutionLinks) {
    const evolvedId = speciesMap.get(link.name);
    const baseId = speciesMap.get(link.evolvesFrom);
    if (evolvedId && baseId) {
      await db
        .update(pokemonSpeciesTable)
        .set({ evolvesIntoId: evolvedId })
        .where(eq(pokemonSpeciesTable.id, baseId));
    }
  }

  console.log("Populating new species into diverse regions...");
  // Spread new species across regions
  const newRegionSpeciesMap: Record<string, string[]> = {
    "Emberveil Meadows": ["Growlithe", "Capsakid", "Gligar"],
    "Aqua Labyrinth": ["Chinchou", "Lotad", "Arcanine"],
    "Thornwood Depths": ["Absol", "Golett", "Delibird"],
    "Storm Peaks": ["Rotom", "Luxray", "Braixen"],
    "Shadow Sanctum": ["Drifloon", "Golett", "Baltoy"],
    "Void Rift": ["Turtonator", "Frigibax", "Magnezone"],
  };

  const allRegions = await db.select().from(regionsTable);
  for (const region of allRegions) {
    const additionalSpeciesNames = newRegionSpeciesMap[region.name] || [];
    if (additionalSpeciesNames.length > 0) {
      const additionalSpeciesIds = additionalSpeciesNames
        .map(name => speciesMap.get(name))
        .filter((id): id is number => id !== undefined);

      const existingSets = new Set(region.wildPokemonSpeciesIds || []);
      for (const aid of additionalSpeciesIds) {
        existingSets.add(aid);
      }
      
      await db
        .update(regionsTable)
        .set({ wildPokemonSpeciesIds: Array.from(existingSets) })
        .where(eq(regionsTable.id, region.id));
    }
  }

  console.log("Expansion successfully injected into db.");
}

expand()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
